# This is a basic workflow to help you get started with Actions

name: Demo-workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1_run_nested_file:
    runs-on: ubuntu-latest
      

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
         with: python-version:'3.9.5'
        

      - name: Run python file
        run: python main.py

        working_directory: script/main/main.py

  job2_run_env_variable:
    day_of_month: june
    greeting_job:
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
      steps:
        - name: "Say Hello"
          run: echo "$Greeting $First_Name. Today is $day_of_month!"
          env:
            First_Name: vaishali






    
